create table public.enquiries (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  business_name text null default 'nullable'::text,
  email text null,
  phone text null default 'nullable'::text,
  problem text null,
  status text null default '"new"'::text,
  constraint enquiries_pkey primary key (id)
);